spring:
  rabbitmq:
    host: 192.168.61.133
    port: 5672
    virtual-host: ZZX
    username: ZZX
    password: JXLZZX79
    publisher-confirm-type: correlated #异步方式
    publisher-returns: true #
    template:
      mandatory: true #定义消息路由失败时的策略。true，则调用ReturnCallback；false：则直接丢弃消息

logging:
  level:
    root: info

