spring:
  rabbitmq:
    host: 192.168.61.133
    port: 5672
    virtual-host: ZZX
    username: ZZX
    password: JXLZZX79
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
